project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks: 
    - notebook: computation/SATP-Methodology.qmd
      title: "SATP Methodology"

number-sections: true

format:
  html:
    comments:
      hypothesis: true
    theme: cosmo
  academic-typst: 
    section-numbering: "1.1.1"
    bibliographystyle: "chicago-author-date"
    include-in-header: 
      - text: '#import "@preview/mitex:0.2.4": *'
  docx: default
  jats: default

  # (other formats)
  # pdf: default

keywords:
  - Soundscape

bibliography: references.bib

execute:
  freeze: auto
  cache: true