project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks: 
    - notebook: computation/SATP-Methodology.ipynb
      title: "SATP Methodology"

number-sections: true

format:
  html:
    comments:
      hypothesis: true
    theme: cosmo
  nature-pdf: default
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



