[project]
name = "satp-methodology"
version = "0.1.0"
requires-python = ">=3.12.2"
dependencies = [
    "circumplex>=0.3.0rc1",
    "ipykernel>=7.0.0a2",
    "jupyter-cache>=1.0.1",
    "num2words>=0.5.14",
    "papermill>=2.6.0",
    # "pipefunc[all]>=0.88.0",
    "qc-procrustes>=1.1.2",
    "rich>=14.2.0",
    "rpy2[all]>=3.5,<3.6",
    "rthor>=0.2.1",
    "scikit-learn>=1.8.0",
    "soundscapy[spi]>=0.8.0rc5",
    # "xarray[accel,types]>=2025.10.1",
    "xarray>=2026.2.0",
]

[tool.uv.sources]
soundscapy = { git = "https://github.com/MitchellAcoustics/Soundscapy", branch = "dev" }
